[package]
name = "ticli"
version = "0.1.0"
edition = "2021"
categories = ["command-line-utilities"]
license = "MIT/Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tikv-client = { git = "https://github.com/tikv/client-rust", rev = "027a7df" }
clap = { version = "4", features = ["wrap_help", "derive"] }
anyhow = "1.0"
tokio = { version = "1.21", features = ["full"] }
owo-colors = "3.5.0"
slog = "2.7"
tabled = { version = "0.9", features = ["color"] }

[build-dependencies]
clap = { version = "4", features = ["wrap_help", "derive"] }
clap_complete = "4"

[profile.release]
lto = true
codegen-units = 1
